// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpSQLtKyqCEAeODqHCQwbNUkRQ8EdYLMo',
    appId: '1:1005962210588:android:18f6137e828531e9ac5ed9',
    messagingSenderId: '1005962210588',
    projectId: 'sign-6795f',
    storageBucket: 'sign-6795f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ7G_V_0JAj1r-EUsadSowERJDjW7HgqI',
    appId: '1:1005962210588:ios:ef19788db2a0ef7bac5ed9',
    messagingSenderId: '1005962210588',
    projectId: 'sign-6795f',
    storageBucket: 'sign-6795f.appspot.com',
    iosBundleId: 'com.example.textsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ7G_V_0JAj1r-EUsadSowERJDjW7HgqI',
    appId: '1:1005962210588:ios:ef19788db2a0ef7bac5ed9',
    messagingSenderId: '1005962210588',
    projectId: 'sign-6795f',
    storageBucket: 'sign-6795f.appspot.com',
    iosBundleId: 'com.example.textsign',
  );

}